INSERT INTO MASTER_TITLE(MASTER_TITLE_ID, DESCRIPTION) VALUES(1,'Flying cow');
INSERT INTO MASTER_TITLE(MASTER_TITLE_ID, DESCRIPTION) VALUES(2,'GoT Winterfell');
INSERT INTO MASTER_TITLE(MASTER_TITLE_ID, DESCRIPTION) VALUES(3,'Siri');
INSERT INTO MASTER_TITLE(MASTER_TITLE_ID, DESCRIPTION) VALUES(4,'Cooking robot');
