INSERT INTO MASTER_TITLE(DESCRIPTION) VALUES
('Flying cow'),
('GoT Winterfell'),
('Apple Siri'),
('Banana guitar'),
('Software bug'),
('The Rolling Stones'),
('Braveheart'),
('Long night'),
('Dirty dancing'),
('Black friday'),
('I am in the laundry machine'),
('The black pearl'),
('Dude, where is my car?'),
('Cooking robot');