CREATE TABLE MASTER_TITLE
(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GAME
(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);