--Physical model for fakeAndDraw backend game
--https://www.lucidchart.com/invitations/accept/e085b14b-0799-4db4-ab1e-483d604b93be

CREATE TABLE MASTER_TITLE
(
    MASTER_TITLE_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(256) NOT NULL,
    PRIMARY KEY (MASTER_TITLE_ID)
);

CREATE TABLE GAME
(
    GAME_ID INT NOT NULL AUTO_INCREMENT,
    GAME_CODE VARCHAR(100) NOT NULL,
    SESSION_ID VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL, 
    PRIMARY KEY (GAME_ID)
);
CREATE INDEX GAME_SESSION_ID ON GAME (SESSION_ID);

CREATE TABLE "MATCH"
(
    MATCH_ID INT NOT NULL AUTO_INCREMENT,
    GAME_ID INT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL, 
    JOIN_TIMEOUT TIMESTAMP NOT NULL, 
    DRAW_TIMEOUT TIMESTAMP NOT NULL, 
    FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID),
    PRIMARY KEY (MATCH_ID)
);

CREATE TABLE PLAYER
(
    PLAYER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    SESSION_ID VARCHAR(100) NOT NULL,
    PRIMARY KEY (PLAYER_ID)
);
CREATE INDEX PLAYER_SESSION_ID ON PLAYER(SESSION_ID);

CREATE TABLE MATCH_PLAYER
(
    MATCH_ID INT NOT NULL,
    PLAYER_ID INT NOT NULL,
    FOREIGN KEY (MATCH_ID) REFERENCES "MATCH"(MATCH_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
    PRIMARY KEY (MATCH_ID,PLAYER_ID)
);
